spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mo_db?useSSL=false&amp&useUnicode=false&amp&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  type-aliases-package: com.midnight.model
  mapper-locations: classpath:com/midnight/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8081
  compression:
    enabled: true
